services:
  temporal:
    depends_on:
      - postgres
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=midas
      - POSTGRES_PWD=secret
      - POSTGRES_SEEDS=postgres
    image: temporalio/auto-setup:1.23
    networks:
      - midas-network
    ports:
      - 7233:7233
    labels:
      kompose.volume.type: configMap
    restart: on-failure
  midas-app:
    build: .
    depends_on:
      - postgres
      - temporal
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - POSTGRES_DB=midasdb
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=midas
      - POSTGRES_URL=postgres:5432
      - TEMPORAL_URL=temporal:7233
    networks:
      - midas-network
    develop:
      watch:
        - action: sync
          path: .
          target: /workspace/app
    restart: on-failure
    labels:
      org.springframework.boot.ignore: true
  postgres:
    image: 'postgres:16'
    environment:
      - POSTGRES_DB=midasdb
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=midas
    ports:
      - 5432:5432
    networks:
      - midas-network
networks:
  midas-network:
    driver: bridge
    name: midas-network
