services:
  postgres:
    image: 'postgres:16'
    environment:
      - POSTGRES_DB=midasdb
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=midas
    ports:
      - 5432:5432
    networks:
      - midas-network
  temporal:
    depends_on:
      - postgres
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=midas
      - POSTGRES_PWD=secret
      - POSTGRES_SEEDS=postgres
    image: temporalio/auto-setup:1.23
    networks:
      - midas-network
    ports:
      - 7233:7233
    labels:
      kompose.volume.type: configMap
    restart: on-failure
networks:
  midas-network:
    driver: bridge
    name: midas-network
